### ISSUE TITLE
romFile expects incorrect size of address bits

### ISSUE THREAD

**Issue by GuzTech** [clash-lang/clash-compiler#407] opened 2018-11-08 13:02 UTC
The first example where romFile is used [here](http://hackage.haskell.org/package/clash-prelude-0.99.3/docs/Clash-Prelude-ROM-File.html) does not work with Clash 0.99.3 (and maybe with earlier versions, but I don't have them here):

```haskell
f :: HiddenClock domain => Signal domain (Unsigned 3) -> Signal domain (Unsigned 9)
f rd = unpack <$> romFile d7 "memory.bin" rd
```

A 3-bit address is enough to address the 7 elements of the memory, but Clash expects it to be the same number of bits as the amount of element (7 bits in this case). So this does compile:

```haskell
f :: HiddenClock domain Source => Signal domain (Unsigned 7) -> Signal domain (Unsigned 9)
f rd = unpack <$> romFile d7 "memory.bin" rd
```

Explicit.romFile does work correctly.

**Comment by martijnbastiaan** [comment] 2018-11-08 13:38
Bug confirmed, thanks! I'll have a look at it tomorrow.

**Comment by martijnbastiaan** [comment] 2019-06-17 14:38
This has been fixed in `master`. Thanks for the report :).

**Comment by dramforever** [comment] 2020-07-03 11:51
It seems that this is still not fixed in 1.2.2? The signature still has `n` as both the ROM size in words and address width: http://hackage.haskell.org/package/clash-prelude-1.2.2/docs/Clash-Prelude.html#v:romFile


```haskell
romFile
  :: (KnownNat m, KnownNat n, HiddenClock dom, HiddenEnable dom)
  => SNat n
  -> FilePath
  -> Signal dom (Unsigned n)
  -> Signal dom (BitVector m)
```

**Comment by dramforever** [comment] 2020-07-03 12:05
The generated code is pretty bad too, at least for Verilog... `c$i` is the super long address which I zero-extended from a nice and short `c$arg`, otherwise it wouldn't compile. Looks like clash arbitrarily just truncates it to 64 bits and indexes into the ROM with that.

Haskell code is essentially `romFile (SNat @3261) "file.txt" . fmap extend`, with 16 bit data width.

<details>

<summary>Verilog, cleaned up a bit</summary>

```verilog
module bad_rom_test
    ( // Inputs
      input  clk // clock
    , input  rst // reset
    , input [11:0] c$arg

      // Outputs
    , output wire [15:0] result
    );
  reg [15:0] x;
  wire signed [63:0] wild;
  wire signed [63:0] c$wild_app_arg;
  wire [3260:0] c$i;

  // romFile begin
  reg [15:0] ROM [0:3261-1];

  initial begin
    $readmemb("file.txt",ROM);
  end

  always @(posedge clk) begin : bad_rom_test_romFile
    x <= ROM[(wild)];
  end
  // romFile end

  assign result = x;

  assign wild = $signed(c$wild_app_arg);

  assign c$i = ({{(3261-12) {1'b0}},c$arg});

  assign c$wild_app_arg = $unsigned(c$i[0+:64]);
endmodule
```

</details>

**Comment by christiaanb** [comment] 2020-07-03 12:42
Right... it seems we only fixed `Clash.Explicit.Rom.File.romFile`, but not `Clash.Rom.File.romFile`.

**Comment by gergoerdi** [comment] 2020-11-28 10:33
Has this been given up on? Since the current `romFile` is unusable, I don't think there's any backwards compatibility to be maintained.

**Comment by christiaanb** [comment] 2020-11-28 10:53
No... simply forgotten. We'll fix it soon

**Comment by gergoerdi** [comment] 2021-03-27 03:44
It seems this bug has made it to 1.4.0. Since in its present form, `romFile` is unusable, there should be no compatibility issues with fixing this in 1.4.1.

**Closed** 2021-03-27 14:32 UTC
Labels: bug
