### ISSUE TITLE
Clash produces name conflicts

### ISSUE THREAD

**Issue by martijnbastiaan** [clash-lang/clash-compiler#1230] opened 2020-03-19 08:15 UTC
~~According to HDL specs a basic identifier `x` and the "same" identifier but extended `\x\` should be considered separate. Some HDL tools seem to have missed the memo though. We should make sure Clash doesn't generate these apparent name conflicts.~~ `x` and `\x\` (basic vs. extended) are the same variable according to (System)Verilog spec and Quartus VHDL implementation, we should account for that during unique id generation.

edit: clarified which spec says what

**Comment by rowanG077** [comment] 2020-03-19 09:27
Duplicate of #823?

**Comment by christiaanb** [comment] 2020-03-19 09:38
@rowanG077 correct

**Closed** 2020-11-06 12:50 UTC
Labels: WIP, bug, external bug
