### ISSUE TITLE
Derived `Eq` does not work for types with a custom bit representation

### ISSUE THREAD

**Issue by pieter-bos** [clash-lang/clash-compiler#2841] opened 2024-11-12 09:09 UTC
If I define a data type and give it a custom bit representation, I cannot use the derived `Eq`. For example:

```haskell
data CompleteAlphabet = A | Z
  deriving Eq

{-# ANN module (DataReprAnn $(liftQ [t|CompleteAlphabet|]) 5
  [ ConstrRepr 'A 0b11111 0b00001 []
  , ConstrRepr 'Z 0b11111 0b11010 []
  ]) #-}

topEntity ::
  Signal System CompleteAlphabet ->
  Signal System Bool
topEntity letter =
  (A ==) <$> letter
```

Gives:

```
Clash: Compiling Mod.topEntity
Clash: Normalization took 0.001s
Clash: Netlist generation took 0.000s

<no location info>: error:
    Clash error call:
    Clash.Backend.Verilog(1195): DataTag (CustomSum "Mod.CompleteAlphabet" (DataRepr' {drType = ConstTy' "Mod.CompleteAlphabet", drSize = 5, drConstrs = [ConstrRepr' {crName = "Mod.A", crPosition = 0, crMask = 31, crValue = 1, crFieldAnns = []},ConstrRepr' {crName = "Mod.Z", crPosition = 1, crMask = 31, crValue = 26, crFieldAnns = []}]}) 5 [(ConstrRepr' {crName = "Mod.A", crPosition = 0, crMask = 31, crValue = 1, crFieldAnns = []},"Mod.A"),(ConstrRepr' {crName = "Mod.Z", crPosition = 1, crMask = 31, crValue = 26, crFieldAnns = []},"Mod.Z")]) (Right (RawIdentifier "letter" Nothing []))
    CallStack (from HasCallStack):
      error, called at src/Clash/Backend/Verilog.hs:1195:13 in clash-lib-1.8.1-deca50a2d0b5b28f53ebb0b53108bb077ebbbf13654c7218daf45426b0e8f8fe:Clash.Backend.Verilog
```

**Comment by leonschoorl** [comment] 2024-11-12 12:41
Duplicate of #2724

**Closed by leonschoorl** 2024-11-12 12:41 UTC
