### ISSUE TITLE
Clarification on supported GHC versions

### ISSUE THREAD

**Issue by mheinzel** [clash-lang/clash-compiler#2494] opened 2023-06-13 12:54 UTC
Which versions exactly are supported at the moment? The table for GHC compatibility in the README is outdated and there are also some related questions about CI.

Current table:

> |      | Linux | Windows | macOS |
> |------|-------|---------|-------|
> | 8.6  | ✔️     | ✔️      | ✔️     |
> | 8.8  | ✔️     | ❌      | ✔️     |
> | 8.10 | ✔️     | ✔️      | ❌     |
> | 9.0  | ✔️     | ✔️²     | ✔️     |
> | 9.2¹ | ❌     | ❌      | ❌     |
> | 9.4³ | ❌     | ❌      | ❌     |
>
>
> ¹ GHC 9.2 contains a regression, rendering Clash error messages indecipherable. This change will be reverted in 9.4.
>
> ² GHC 9.0.2 on Windows fails to compile `clash-cores`. We therefore don't run the Clash testsuite on CI for this combination.
>
> ³ A critical dependency of Clash, `hint`, has not yet been ported to GHC 9.4.

### GHC 9.2

Now seems to be supported, as it's tested in CI for all three platforms. So ❌ is outdated. However, the footnote around the regression for error messages still applies, so maybe it should not be ✔️, either?

### GHC 9.4

Seems to be supported, so probably should be ✔️. Has the issue with `hint` been resolved? If so, footnote 3 can be removed.

Surprisingly, CI only runs the Windows and macOS tests (added in https://github.com/clash-lang/clash-compiler/pull/2367/commits/4fa47b41f0319e34f21f95ec315f9917789dcc3d). Is there any reason for not running the Linux tests or has it just been forgotten?

### GHC 9.6

~~Not run in CI yet, but if I remember correctly, it at least works for @alex-mckenna on Linux (via the Nix flake). Does this already warrant a ✔️ on Linux? Can we add tests for 9.6 to CI?~~
I just saw that GHC 9.6 support has been added, but [the GitHub Action depends on a Stackage nightly for GHC 9.6](https://github.com/clash-lang/clash-compiler/pull/2467/files#diff-037ea159eb0a7cb0ac23b851e66bee30fb838ee8d0d99fa331a1ba65283d37f7), which still doesn't exist. Not sure how the GitLab CI is run, but seems like a ✔️ for Linux is justified? 

Thanks!

**Comment by alex-mckenna** [comment] 2023-06-13 15:57
I think we can add a tick for the others and leave a footnote on any configuration not used in CI. It _should_ just work, but it's always good to tell people on other OS that we won't know if there's some weird edge-case regression. I personally can indeed build all the packages and run the testsuite on my machine, so I'm pretty confident in the 9.6 on Linux

**Comment by martijnbastiaan** [comment] 2023-06-13 18:17
> Now seems to be supported, as it's tested in CI for all three platforms. So x is outdated. However, the footnote around the regression for error messages still applies, so maybe it should not be heavy_check_mark, either?

I feel :heavy_check_mark: is fine, but we should just attach the footnote to each tick.

> Seems to be supported, so probably should be heavy_check_mark. Has the issue with hint been resolved? If so, footnote 3 can be removed.

@christiaanb has proposed PRs that implement support for newer GHCs, but they haven't been merged/released yet.

> Surprisingly, CI only runs the Windows and macOS tests (added in https://github.com/clash-lang/clash-compiler/commit/4fa47b41f0319e34f21f95ec315f9917789dcc3d). Is there any reason for not running the Linux tests or has it just been forgotten?

Seems like an oversight!

> Not sure how the GitLab CI is run, but seems like a heavy_check_mark for Linux is justified?

Yes. But also note that there is no released version of Clash with GHC 9.4+ support (mostly due to `hint`). We should probably clarify this in a new column.

**Comment by martijnbastiaan** [comment] 2023-06-17 17:33
> @christiaanb has proposed PRs that implement support for newer GHCs, but they haven't been merged/released yet.

@mheinzel @alex-mckenna A new `hint` release has been made on Hackage, so we should be able to remove the custom dependency :tada:.

**Closed** 2023-06-18 18:52 UTC
Labels: enhancement
